services:
  postgres:
    image: postgres:16
    container_name: postgresdb-template
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template_db
    ports:
      - "5432:5432"

volumes:
  pg_data:
    name: template-postgres-data