services:
  postgres:
    image: postgres:16
    container_name: flashbox-database
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: flashbox
      POSTGRES_PASSWORD: flashbox
      POSTGRES_DB: flashbox_db
    ports:
      - "5432:5432"

volumes:
  pg_data:
    name: flashbox-postgres-data