"""adding relationship between user table and flashcard and flashcard_stack tables

Revision ID: 31ae1a51b70d
Revises: 329c76f689b2
Create Date: 2025-10-28 00:43:30.855896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ae1a51b70d'
down_revision: Union[str, None] = '329c76f689b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=555),
               existing_nullable=False)
    op.add_column('flashcard_stacks', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'flashcard_stacks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('flashcards', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'flashcards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.drop_column('flashcards', 'user_id')
    op.drop_constraint(None, 'flashcard_stacks', type_='foreignkey')
    op.drop_column('flashcard_stacks', 'user_id')
    op.alter_column('auth_user', 'refresh_token',
               existing_type=sa.String(length=555),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
