"""create flashcard and flashcard_stack tables

Revision ID: 4881435d4ffa
Revises: 5c74c9c69818
Create Date: 2025-10-23 20:33:13.347494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4881435d4ffa'
down_revision: Union[str, None] = 'e99e5b8903d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_stacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('main_language', sa.String(length=65), nullable=False),
    sa.Column('learning_language', sa.String(length=65), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_to_learn', sa.String(length=50), nullable=False),
    sa.Column('translation', sa.String(length=50), nullable=False),
    sa.Column('example', sa.String(length=100), nullable=True),
    sa.Column('flashcard_stack_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_stack_id'], ['flashcard_stacks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcards')
    op.drop_table('flashcard_stacks')
    # ### end Alembic commands ###
